### PR TITLE
Update scale and orientation of STL files.

### PR DESCRIPTION
**Pull request by bperseghetti**
This is split out from a previous closed [PR 167](https://github.com/iRobotEducation/create3_docs/pull/167) and updates the scale and orientation of the STL files.

### CODE REVIEW

**Comment by shamlian** [comment]
What is the goal of this PR? Some of the files that are marked as changed are shown in a more sliceable orientation, some are not, and others with slightly different file sizes appear unchanged.

Improved orientation for slicing:
C3-Cargo-Bay-With-Caster.stl
C3-Caster-Lock.stl
C3-JetsonXavierNX-Mount.stl
C3-Rear-Caster-Attachment-Latch.stl
C3-Rear-Caster-Attachment.stl
C3-RPi-Mount-20211022.stl
C3-RPi-Mount-Small-20211022.stl
C3-RPLidar-A1-Mount.stl

Worse orientation for slicing (shown as mounted, though -- maybe that is the intent?)
C3-OAK-D-Lite-Mount.stl
C3-OAK-D-Mount.stl
C3-RealSense-D435-Mount.stl
C3-Stud-Mount.stl

Needlessly changed
C3-RPLidar-A1-USB-Mount.stl

**Comment by shamlian** [comment]
I didn't notice any scale changes (just changes in orientation); which files were changed in scale? Note that I tested only in Cura.

**Review by shamlian — COMMENTED** [review]
What is the goal of this PR? Some of the files that are marked as changed are shown in a more sliceable orientation, some are not, and others with slightly different file sizes appear unchanged.

Improved orientation for slicing:
C3-Cargo-Bay-With-Caster.stl
C3-Caster-Lock.stl
C3-JetsonXavierNX-Mount.stl
C3-Rear-Caster-Attachment-Latch.stl
C3-Rear-Caster-Attachment.stl
C3-RPi-Mount-20211022.stl
C3-RPi-Mount-Small-20211022.stl
C3-RPLidar-A1-Mount.stl

Worse orientation for slicing (shown as mounted, though -- maybe that is the intent?)
C3-OAK-D-Lite-Mount.stl
C3-OAK-D-Mount.stl
C3-RealSense-D435-Mount.stl
C3-Stud-Mount.stl

Needlessly changed
C3-RPLidar-A1-USB-Mount.stl

Which files changed in scale? I only noticed orientation changes. Checked using Cura, maybe this was abstracted away.

**Comment by bperseghetti** [comment]
> 

I believe there are 3 main goals to this PR:

1. Make all models use correct "natural orientations" for clarity of the correct positioning of the model in end use.
2. Fix units to all be based in mm.
3. Allow for visualization of the files using gihub's native STL viewer (in documentation or otherwise, see examples below).

First, for different types of printers different orientations might be preferred. For instance, I use both SLA and FDM printers. When using an SLA printer I would change most of the orientations to reduce on print time in comparison to an FDM. I believe that they should follow "true orientation" as much as possible and leave any rotations desired based on the slicer/printer configuration. Furthermore, it more readily allows these models to be included in simulation or rviz files like URDF or SDF file for an overall robot platform visualization. Also when imported into fusion many models were significantly below the XY plane as seen in an example of the C3-OAK-D-Lite-Mount.stl in [Blender](https://www.blender.org/), with the highlighted one in orange being the one currently in the repo and significantly under the build/XY plane. 
image


Second, some of these models when imported into Fusion360 came up with imported units that were cm and made them exceedingly large if one were to slice/print on a device that does not auto-scale to reasonable units.

And lastly (third), in the subsequent comment are some examples of how the models look now in the github native viewer that can be strategically added to areas of the documentation later (if desired) or just allow for better browsing.

**Comment by bperseghetti** [comment]
Some clickable examples for github's STL viewer:
Updated:
https://github.com/rudislabs/create3_docs/blob/stl_update/docs/hw/data/brackets/C3-RPi-Mount-20211022.stl
Old:
https://github.com/iRobotEducation/create3_docs/blob/main/docs/hw/data/brackets/C3-RPi-Mount-20211022.stl

Updated:
https://github.com/rudislabs/create3_docs/blob/stl_update/docs/hw/data/brackets/C3-RPLidar-A1-Mount.stl
Old:
https://github.com/iRobotEducation/create3_docs/blob/main/docs/hw/data/brackets/C3-RPLidar-A1-Mount.stl

Updated:
https://github.com/rudislabs/create3_docs/blob/stl_update/docs/hw/data/brackets/C3-OAK-D-Mount.stl
Old:
https://github.com/iRobotEducation/create3_docs/blob/main/docs/hw/data/brackets/C3-OAK-D-Mount.stl

**Comment by shamlian** [comment]
Before I approve this review, I'm just doing a print of the changed files to ensure nothing unexpected changed.

**Review by shamlian — APPROVED** [review]

**Pull request merged**
